[ENG-8070][INTERNAL] Fix PR title check to validate Clickup task ID in hudi-internal (#618)

diff --git a/.github/workflows/pr_compliance.yml b/.github/workflows/pr_compliance.yml
--- a/.github/workflows/pr_compliance.yml
+++ b/.github/workflows/pr_compliance.yml
@@ -8,9 +8,6 @@ on:
 jobs:
   validate-pr:
     runs-on: ubuntu-latest
-    if: >
-      !contains(github.event.pull_request.title, '[BREAKGLASS]') &&
-      !contains(github.event.pull_request.title, '[AUDIT-')
     env:
       GH_TOKEN: ${{ github.token }}
       REQUEST_BODY: ${{ github.event.pull_request.body }}
@@ -18,23 +15,52 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v3
+      - name: Check Clickup task ID in PR title
+        run: |
+          set -e
+          PR_TITLE="${{ github.event.pull_request.title }}"
+          if [[ ! "$PR_TITLE" =~ ^(\[AUDIT-|\[ONHS-|\[ENG-) ]]; then
+            echo "PR title does not start with Clickup task ID, i.e., [AUDIT-<ID>], [ONHS-<ID>], or [ENG-<ID>]."
+            echo "Please check Hudi internal PR process: https://github.com/onehouseinc/hudi-internal?tab=readme-ov-file#hudi-internal-pr-process"
+            exit 1
+          fi
+          if [[ "$PR_TITLE" == "[AUDIT-"* ]]; then
+            echo "skip-title-extraction=true" >> $GITHUB_ENV
+            echo "Skipping PR title extraction for AUDIT related changes."
+          else
+            echo "skip-title-extraction=false" >> $GITHUB_ENV
+          fi
+      - name: Extract Hudi PR title
+        id: extract-hudi-pr-title
+        if: env.skip-title-extraction == 'false'
+        run: |
+          PR_TITLE="${{ github.event.pull_request.title }}"
+          HUDI_PR_TITLE=$(echo "$PR_TITLE" | cut -d ']' -f2-)
+          echo "Extracted title after the Clickup task ID: $HUDI_PR_TITLE"
+          if [[ "$HUDI_PR_TITLE" == "[INTERNAL]"* ]] || [[ "$HUDI_PR_TITLE" == "[CHERRYPICK]"* ]]; then
+            echo "skip-hudi-title-check=true" >> $GITHUB_ENV
+            echo "Skipping Hudi title check for internal or cherrypick changes."
+          else
+            echo "skip-hudi-title-check=false" >> $GITHUB_ENV
+            echo "title=${HUDI_PR_TITLE}" >> $GITHUB_OUTPUT
+          fi
       - name: Check companion PR in Hudi OSS
+        if: env.skip-hudi-title-check == 'false'
         run: |
           set -e
           export HUDI_OSS_PR_ID=$(echo "${{ github.event.pull_request.body }}" | grep -Eo 'apache/hudi#[0-9]+|https://github.com/apache/hudi/pull/[0-9]+' | head -n 1)
           export TMP_HUDI_OSS_PR_TITLE=$(echo $HUDI_OSS_PR_ID | grep -Eo '[0-9]+' | xargs -I {} gh pr view {} --repo apache/hudi | head -n 1 | grep -Eo '\[.*')
           echo "HUDI_OSS_PR_TITLE=$TMP_HUDI_OSS_PR_TITLE" >> $GITHUB_ENV
-          ((([ -n "$HUDI_OSS_PR_ID" ] || (echo "Unable to find companion Hudi OSS PR based on the PR description" && exit 1)) &&
+          ((([ -n "$HUDI_OSS_PR_ID" ] || (echo "Unable to find companion Hudi OSS PR based on the PR description. Please check Hudi internal PR process: https://github.com/onehouseinc/hudi-internal?tab=readme-ov-file#hudi-internal-pr-process" && exit 1)) &&
           [ -n "$TMP_HUDI_OSS_PR_TITLE" ] &&
           echo "Companion Hudi OSS PR is: $HUDI_OSS_PR_ID $TMP_HUDI_OSS_PR_TITLE") ||
-          (echo "Unable to extract title of the Hudi OSS PR: $HUDI_OSS_PR_ID" && exit 1))
+          (echo "Unable to extract title of the Hudi OSS PR: $HUDI_OSS_PR_ID. Please check Hudi internal PR process: https://github.com/onehouseinc/hudi-internal?tab=readme-ov-file#hudi-internal-pr-process" && exit 1))
       - name: Check PR title identity
         run: |
-          if [[ "$HUDI_OSS_PR_TITLE" == "${{ github.event.pull_request.title }}" ]]; then
+          if [[ "$HUDI_OSS_PR_TITLE" == "${{ steps.extract-hudi-pr-title.outputs.title }}" ]]; then
             echo "PR title is the same as the companion Hudi OSS PR. Validation passes."
           else
             echo "PR title is different from the companion Hudi OSS PR. Validation fails."
+            echo "Please check Hudi internal PR process: https://github.com/onehouseinc/hudi-internal?tab=readme-ov-file#hudi-internal-pr-process"
             exit 1
           fi
-      - name: Check PR title and description
-        run: python3 scripts/pr_compliance.py
