trying to show error message

diff --git a/.github/workflows/pr_compliance.yml b/.github/workflows/pr_compliance.yml
--- a/.github/workflows/pr_compliance.yml
+++ b/.github/workflows/pr_compliance.yml
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v3
       - name: run script
-        run: python scripts/pr_compliance.py
+        run: python scripts/pr_compliance.py > test.log || echo "::error $(cat test.log)" && exit 1
 
 
 
